region           = "us-east-1"
env              = "dev"
ecs_cluster_name = "stockwiz-dev"   
alb_arn_suffix   = ""               
ecs_service_name         = "stockwiz-service"
target_group_arn_suffix  = ""
