aws_region          = "us-east-1"
environment         = "testing"
vpc_cidr            = "10.1.0.0/16"
public_subnet_cidrs = ["10.1.0.0/25", "10.1.0.128/25"]
azs = ["us-east-1a", "us-east-1b"]
instance_type     = "t2.micro"
instance_count    = 1
enable_alb        = true
enable_asg        = true
min_instances     = 1
max_instances     = 3
desired_instances = 1
